#Port
server.port=8080
upload.dir=D:\\Project1\\mp3Song
upload.image=D:\\Project1\\images

spring.application.name=Project1
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

spring.datasource.url=jdbc:postgresql://ep-super-salad-aepkhglh-pooler.c-2.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_hk9M4PXbDBar&sslmode=require&channelBinding=require
# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true